name: Grammar
on: [pull_request]

jobs:    
  yaspeller:
    runs-on: ubuntu-latest
    name: Check Spelling
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: npm install -g yaspeller
      - run: yaspeller -l ru ru/articles/
      - run: yaspeller -l en en/articles/
